name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install build tooling
        run: python -m pip install build
      - name: Run hook tests
        run: python3 plugins/secrets_scanner/tests/read_hook_test.py --suite basic
      - name: Build distribution artifacts
        run: python -m build

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build distribution artifacts
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
