name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install build tooling
        run: python -m pip install build
      - name: Run hook tests
        run: python3 read_hook_test.py --suite basic
      - name: Build distribution artifacts
        run: python -m build

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install publishing tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
      - name: Build distribution artifacts
        run: python -m build
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
